name: CI-CD Online Sports

on:
  push:
    branches: [ "main" ]

jobs:
  ci:
    name: CI - Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Backend
      - name: Instalar dependencias backend
        working-directory: backend
        run: npm install

      - name: Build backend
        working-directory: backend
        run: npm run build || echo "No build backend"

      # Frontend (solo build, NO deploy)
      - name: Instalar dependencias frontend
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  build_and_push_backend:
    name: Build & Push Backend Image
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagen backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/online-sports:latest .

      - name: Push imagen backend
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/online-sports:latest

